// Generated by https://quicktype.io

export interface ConfigManifestV2 {
    architecture:     string;
    config:           ContainerConf;
    container:        string;
    container_config: ContainerConf;
    created:          string;
    docker_version:   string;
    history:          History[];
    os:               string;
    rootfs:           Rootfs;
}

export interface ContainerConf {
    Hostname:     string;
    Domainname:   string;
    User:         string;
    AttachStdin:  boolean;
    AttachStdout: boolean;
    AttachStderr: boolean;
    Tty:          boolean;
    OpenStdin:    boolean;
    StdinOnce:    boolean;
    Env:          string[];
    Cmd:          string[];
    Image:        string;
    Volumes:      null;
    WorkingDir:   string;
    Entrypoint:   string[];
    OnBuild:      null;
    Labels:       Labels;
}

export interface Labels {
    "io.balena.architecture": string;
    "io.balena.device-type":  string;
    "io.balena.qemu.version": string;
}

export interface History {
    created:      string;
    created_by:   string;
    empty_layer?: boolean;
}

export interface Rootfs {
    type:     string;
    diff_ids: string[];
}
